# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/skills"]
    end
  end

  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "6b6d1202ffbe85abece3e350a7105d249f77ccdaee3fa5ef8c608fca388d27f1"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "09526019b522314000c830b03b9a3fca47ba05a1f2c683282493ee7f63a99dc7"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c7121b5bd8d1f115d8ae0be2b65cce85c1d558cf783eb060bf7ab1b49f9fdaf"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8bcd0e382bf3127a7836ad60cc0dc8540dc23b32dd19baf299272c6e74fbbfb3"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skills"
  desc "Install agent skills into your projects and keep them up to date"
  homepage "https://github.com/madalinpopa/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills"

  # No zap stanza required
end
