# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills" do
  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "ace4783ed10f540be2e9b8a1a30d0181b6a540ea9ad9d5ad960252490c0debce"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a526866bb778dd6d6ab3bff1c45da7cf234a61052660579305042f42c6879fb"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9bf09f725cc7d5a264e882b8d3d68cb970805e4337613d0e628fe57cadf17c50"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "07b198677e0a535e058c4d895e1a432191955792d8c7ef205688ab50ba3eddb7"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skills"
  desc "Install agent skills into your projects and keep them up to date"
  homepage "https://github.com/madalinpopa/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skills"]
    end
  end

  # No zap stanza required
end
