# This file was generated by GoReleaser. DO NOT EDIT.
cask "skills" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/skills"]
    end
  end

  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "8061a63647d2c99da52e2525e741230fbdd9ccb34544a5604440c5ec1c630b91"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9ff5b950f5e8d2b343604f8b877001540facfa62a13948844432fa03c7bfbfc"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7db26503d07d2c4334f8f6c5201d7f4cd8cc287da8f392ed28c1cf902638c808"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "883e90de3b683b942484fafffdab23dc952b690fe141dd1b93202e11c66d7205"
      url "https://github.com/madalinpopa/skills/releases/download/v#{version}/skills_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skills"
  desc "Install agent skills into your projects and keep them up to date"
  homepage "https://github.com/madalinpopa/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skills"

  # No zap stanza required
end
